### PR TITLE
 Implemented Denied Page for Restricted Routes

### LINKED ISSUE #19: Create a Denied Page for Inaccessible Routes
I would like to add a dedicated "Denied" page that will be displayed when users attempt to access routes they are not authorized to view. This page will clearly inform users that they do not have the necessary permissions to access the requested route.

The proposed flow:

+ Users without the required access rights will be redirected to /denied when they attempt to access restricted routes.
+ The denied page will be a simple and informative component that explains the reason for the redirection.

This feature will improve user experience by providing feedback for unauthorized access instead of silently redirecting them elsewhere.

Please assign me this issue under Hacktoberfest

### PR DESCRIPTION
**Pull request by Anshul-Sharma01**
This PR introduces a dedicated Denied Page to handle cases where users attempt to access restricted routes based on their gender or authentication status. Instead of redirecting users to the landing page, the system will now show a denied page for improved user experience and better route protection. This enhancement also leverages a RequireAuth component for cleaner and more maintainable route handling logic.

Changes Made:

- Created Denied component to display a message when access is denied.
- Replaced existing landing page redirection with the new denied page for restricted routes.
- Updated route protection using RequireAuth to handle gender-based and authentication-based restrictions.
- Ensured unauthorized users are shown the denied page instead of the landing page.
- Updated the route configuration to maintain a clean and modular approach.

Screenshot 2024-10-01 145611

This PR closes #19

### CODE REVIEW

**Comment by rishyym0927** [comment]
Hi @Anshul-Sharma01,

Your page looks fantastic! However, I've noticed a bug in your code. The issue is that the `user` object from the `AuthContext` is being accessed immediately in the `RequireAuth` component. This can cause it to be `null` if the user data hasn’t loaded yet. To fix this, we should add a 2-second delay before accessing the user context.

That said, this approach isn't the most optimized solution. I recommend removing the `RequireAuth` component altogether and applying the restrictions directly using the `user` from `App.jsx`. This will simplify the implementation and prevent any bugs.

**Comment by Anshul-Sharma01** [comment]
Hi @rishyym0927,

Thanks for the feedback! I have made the requested changes by:

- Removing the RequireAuth component.
- Directly applying the restrictions in App.jsx based on the user object from AuthContext.

Let me know if any further changes are needed!

**Comment by rishyym0927** [comment]
let me check the code, it will take some time , we will megre it as soon as possible

**Comment by Anshul-Sharma01** [comment]
I’ve squashed all the commits and removed the redundant imports. Thank you for your guidance and patience—I'm learning a lot through my first open-source contribution!

**Pull request merged**
