### PR TITLE
Updated README.md

### PR DESCRIPTION
**Pull request by In-Saiyan**
# Description
- Added Screenshot
- Added Banner created in Figma
- Added directory tree
- Added User Interface GIF
- Added Contributers Section
- Improved Navigation

# Features completed
- [x] Refactor the text to improve grammar, structure, and clarity.
- [x] Add sample screenshots to visually represent the frontend UI.
- [x] Include a "Contributors" section with contributor images.
- [x] Review and update the table for routing to ensure it is more user-friendly.  

## [Preview](https://github.com/In-Saiyan/Affinity_frontend/blob/dev/README.md)

### CODE REVIEW

**Comment by In-Saiyan** [comment]
There is also a directory-tree.png but it is not loading in MD no matter what I do.
(It loads up in edit mode on GitHub and also in VS Code markdown preview.)
directory-tree

**Comment by rishyym0927** [comment]
@In-Saiyan, you've done excellent work! However, I noticed that the image files in your repository are not compressed. You can either compress the images or, as a current suggestion, upload them directly through GitHub's README.md editor. This will simplify the process and ensure GitHub hosts them efficiently.

**Comment by In-Saiyan** [comment]
@rishyym0927 sure!

**Comment by In-Saiyan** [comment]
because the table uses images tags instead of markdown tags

**Comment by rishyym0927** [comment]
You have the liberty, either you compress it or upload it straight.

**Comment by In-Saiyan** [comment]
@rishyym0927 done

**Pull request closed without merging**
