### PR TITLE
Improved Readme.md

### LINKED ISSUE #29: Improve README.md for Affinity Frontend: Make It More Professional and Add Visuals
**Issue Title:** Improve README.md for Affinity Frontend: Make It More Professional and Add Visuals

### **Description**
The current `README.md` file for the Affinity Frontend project needs to be updated to make it more professional and readable. The goal is to enhance its presentation by:
1. Improving the overall formatting and organization.
2. Adding sample images that showcase the project interface.
3. Including contributor images to highlight team members.
4. Clarifying the sections on installation, usage, and routing.
   
### **Task List**
- [ ] Refactor the text to improve grammar, structure, and clarity.
- [ ] Add sample screenshots to visually represent the frontend UI.
- [ ] Include a "Contributors" section with contributor images.
- [ ] Review and update the table for routing to ensure it is more user-friendly.

### **Expected Outcome**
The updated `README.md` should provide clear, professional guidance for developers looking to contribute and for users interested in understanding the project better. Additionally, the visual elements should make the repository more engaging and informative.

### PR DESCRIPTION
**Pull request by Thunder-Blaze**
## Problem
Closes #29 

## What I did
- Added a Banner for Affinity rather than just a Heading, It can be modified later on when a new banner is released
- Improved some parts of text 
- Added Contibutiors Section
- Made a Better Navigation
- Added Preview for Main Pages of the Website

README Inspired by [Hyprdots](https://github.com/prasanthrangan/hyprdots)

I don't know what to do in "Review and update the table for routing to ensure it is more user-friendly"
So if you could clarify a bit more, I might be able to do that as well

### CODE REVIEW

**Comment by Thunder-Blaze** [comment]
Sir, I think I did what I understood by routing (hyperlinking it to respective jsx files)
Can you check is this good ?

**Comment by rishyym0927** [comment]
"Review and update the routing table to improve user-friendliness" Since the project contains multiple pages, the README should clearly outline which routes redirect to each specific page.

Also your pr is under review , we will update you shortly.

**Comment by Thunder-Blaze** [comment]
Oh then I think, I did added hyperlinks to each specific page so that the user can know which route is redirecting to which file

Ok sure

**Comment by rishyym0927** [comment]
@Thunder-Blaze, great job on your work! The PRs will be merged once we have received all submissions.

**Comment by Thunder-Blaze** [comment]
@rishyym0927 Ok sir, I also optimised the images and btw more previews can be shown if you want (There are 8-9 screenshots in assets folder) but I thought to show only the main 4 pages in Preview

**Comment by rishyym0927** [comment]
4 is better ig

**Pull request merged**
