### PR TITLE
Form validations rules added to registration forms

### PR DESCRIPTION
**Pull request by Kp779**
Solved issue #18 - Integrate form Validation in forms of registration process

This PR adds the validations to the form fields that are needed in the registration process. As per the mentioned requirements the validations have been handled on the frontend side in React. Made sure that all different kinds of conditions are covered to ensure validations work in all those conditions. Ensured that there are no disruptions to the UI of the project when validation messages appear.

Implementing validations in registration forms significantly enhances data integrity and user experience. By ensuring that users provide accurate and complete information, validations prevent errors and guide users with clear feedback on their input. This leads to increased trust in the application, as users feel more confident in its reliability.

### CODE REVIEW

**Comment by rishyym0927** [comment]
Hey @Kp779 

This is perfect, but the in the age field its showing and Im not to able to  fill the box, please fix the bug and I will merge it

**Comment by Kp779** [comment]
@rishyym0927 I have resolved the age input box issue. The checks are working well. Multiple checks to it was causing the error.

**Comment by rishyym0927** [comment]
Cool everything works well now,  can you squash your commits and have a clean commit history?

**Comment by Kp779** [comment]
I am sorry but I'm not sure how that's done.

**Comment by rishyym0927** [comment]
okay

**Pull request merged**
