### PR TITLE
404page/custom 4o4

### PR DESCRIPTION
**Pull request by piyusss11**
#What does this PR do?
This PR adds a custom error page which can be used for showing errors and redirecting to "/" route. The error page can be found on "/error" route. It follows the color palette of the app and is responsive for mobile devices as well.

For Desktop

Screenshot (80)

For Mobile
 
Screenshot (79)

### CODE REVIEW

**Comment by rishyym0927** [comment]
Hello @piyusss11,

Please create pull requests (PRs) only for the issues that have been assigned to you. Once an issue is assigned, feel free to begin working on it.

Additionally, I'd encourage you to be more creative in your approach, especially considering the current design. Looking forward to seeing your contributions!

**Comment by piyusss11** [comment]
> Hello @piyusss11,
> 
> Please create pull requests (PRs) only for the issues that have been assigned to you. Once an issue is assigned, feel free to begin working on it.
> 
> Additionally, I'd encourage you to be more creative in your approach, especially considering the current design. Looking forward to seeing your contributions!


okay noted. should I revamp it and create another PR for this issue?

**Comment by Sidharth-Singh10** [comment]
@piyusss11, feel free to revamp the design. I believe it would be better if you could share your design first for review. Looking forward to your input!

**Comment by piyusss11** [comment]
> @piyusss11, feel free to revamp the design. I believe it would be better if you could share your design first for review. Looking forward to your input!

Since it's an error page that is why I kept it minimalistic, I feel people will not spend more than 4-5 seconds before going back to the dashboard. so filling it up with texts or other details will derail the user experience. 

If not then I'll add or make changes in the ui.

**Comment by rishyym0927** [comment]
> > @piyusss11, feel free to revamp the design. I believe it would be better if you could share your design first for review. Looking forward to your input!
> 
> Since it's an error page that is why I kept it minimalistic, I feel people will not spend more than 4-5 seconds before going back to the dashboard. so filling it up with texts or other details will derail the user experience.
> 
> If not then I'll add or make changes in the ui.


This PR is closed now. Please comment your proposal on the respective issue and wait to be assigned before proceeding.

**Pull request closed without merging**
